//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_Db_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaLineas
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Total { get; set; }
        public decimal Costo { get; set; }
        public int ArticulosId { get; set; }
        public int FacturaId { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
