//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_Db_EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModelDBContainer : DbContext
    {
        public ModelDBContainer()
            : base("name=ModelDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<UnidadMedidad> UnidadMedidad { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Presentacion> Presentacion { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<BodegaArticulo> BodegaArticulo { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<FacturaLineas> FacturaLineas { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Minicipio> Minicipio { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Recibo> Recibo { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<Departamento_Result> sp_sel_Departamento(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Departamento_Result>("sp_sel_Departamento", idParameter);
        }
    }
}
