//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_Db_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public int Id { get; set; }
        public string Norecibo { get; set; }
        public System.DateTime FechaRecibo { get; set; }
        public decimal Efectivo { get; set; }
        public decimal Cheque { get; set; }
        public decimal Deposito { get; set; }
        public decimal Total { get; set; }
        public decimal MontoIR { get; set; }
        public string NoIR { get; set; }
        public decimal MontoIMI { get; set; }
        public string NoIMI { get; set; }
        public decimal Saldo { get; set; }
        public int Estado { get; set; }
        public int FacturaId { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
