//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_Db_EDM.GestionUsuario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccesoContainer : DbContext
    {
        public AccesoContainer()
            : base("name=AccesoContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FuncionDeAcceso> FuncionDeAcceso { get; set; }
        public virtual DbSet<FuncionAsignada> FuncionAsignada { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
